# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
 languageCode: zh-Hans
 contentDir: content/zh
 title: 中文主页
 params:
   description: Homepage in Chinese
 menu:
   main:
      - name: 主页
        url: '#about'
        weight: 10
      - name: 荣誉
        url: '#accomplishments'
        weight: 20
      - name: 研究经历
        url: '#experience'
        weight: 30
      - name: 论文
        url: '#featured'
        weight: 40
      - name: 项目
        url: '#projects'
        weight: 50
      - name: 联系方式
        url: '#contact'
        weight: 60
